language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo clean && hexo g 

after_script:
  - cd ./public
  - git init
  - git config user.name "JasonRen23"
  - git config user.email "zhicheng_ren@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    # - master
    - hexo
env:
 global:
   - GH_REF: github.com/JasonRen23/JasonRen23.github.io.git
