language: node_js
node_js: 
  - 5.1.1

# Travis-CI Caching
cache:
  directories:
    - ~/.npm
    - node_modules
git:
   depth: 1
addons:
   apt:
     packages:
        - sshpass

# S: Build Lifecycle
before_install:
    - npm install -g hexo hexo-cli gulp

install:
  - npm install

script:
 - hexo cl
 - hexo g
 - gulp

after_script:
  - cd public
  - git init
  - git config user.name "zhicren"
  - git config user.email "zhicheng_ren@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - sshpass -e ssh -q -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh 2 > /dev/null
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/JasonRen23/JasonRen23.github.io.git
   - secure: "DF/FYOv2tFQy9jZqO8py3HyMxu9U9Su6pNficnyYaXiKzDZANMaZ69MRohMx5gjbaqe8eyBEigPhUbjzQMk/dnBzlbxNjUm5smNMptfAXvGwsW8ylJ5c0mbFWJXoaz+icVZbvPRQkNzCxGJFzd6pmE49KuRKU1dBwkd4RD8X7ofj476srvJsyIjPpsyAFjA7Ryhj+97JYXGnQcEpCB3Y3omLLzIn5kYqE7dgeRt54+e8Ywgy2YAdhaH975fwNq6mYI8j/ubl/l8XwIysMlVQqd6tXTJzPrRcVpMvyz099Hi/TDyM87ClAAffvuzuj8FraeM9mw8dRB6GVtb/YyFrWfM7qcMQEDUJZCarWrPPnARe9pXQFkcbL5ReqsQd9dJHjmBNnEXAsWzhE//V9aKqzoE4MonIdTPZ9gR4mAtgZdDHkfzaQjGj9oTDnXhE5IjZGEWHdmgreKO/XSm0qtYtXen2K/Ky12k53aeiHf4ENU5qR0Ihlop4KEWQrvVSUi1E3tlHL4Du4e2sFIhZlHymoIKE0kE0/PPMJjaYpr26cas9Z3SfEifL3WtN7el1e93rwVVSbb/6m50ovpKW0uadO5XMBs5x2czXzT8FHdLCzjENF/9AznadbyJenss2RBcqlZqfWAl92yaQ1JsLJ04ohddK17wFugfLiK0TD376afY=" 
